version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 1s
      retries: 120
    restart: on-failure
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 15672:15672

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "payment_success:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  app-rmq:
    image: rebrain/rmq:${VERSION}
    ports:
      - 8000:8000
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - ./rmq/config/env.dev

  app-kafka:
    image: rebrain/kafka:${VERSION}
    ports:
      - 8001:8000
    depends_on:
      - kafka
    env_file:
      - ./kafka/config/env.dev